package com.synchrony.inclusion.ai;

import java.util.List;

/**
 * Output of the Explainable AI orchestrator.
 *
 * @param rationale        plain-language decision rationale
 * @param principalReasons the specific principal reasons for the outcome
 * @param recourseSummary  a short summary of the path to approval, empty for approvals
 * @param source           BEDROCK when generated by the model, FALLBACK when produced by the deterministic template
 */
public record XaiResult(
        String rationale,
        List<String> principalReasons,
        String recourseSummary,
        String source
) {
}
